name: Java CI

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Increment version
        id: version
        uses: pdodds/Bump-N-Tag-Version@master
        with:
          file_name: './VERSION'
          tag_version: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Export VERSION
        run: |
          echo "::set-env name=CURRENT_VERSION::$(cat ./VERSION)"
        shell: bash
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn versions:set -DnewVersion=$CURRENT_VERSION
          mvn install
