name: Java CI

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v3
      - name: Increment version
        id: version
        uses: pdodds/Bump-N-Tag-Version@master
        with:
          file_name: './VERSION'
          tag_version: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export CURRENT_VERSION=`cat VERSION`
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>kodexa-ai</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn versions:set -DnewVersion=$CURRENT_VERSION
          mvn install deploy site
          mkdir -p ./target/site/repo/com
          cp -r ~/.m2/repository/com/kodexa ./target/site/repo/com
      - name: Deploy GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site
          keep_files: true
